name: Here-Doc Breakout (Minimal)

on:
  issues:
    types: [opened, edited]

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: SAFE — print issue body via here-string
        shell: bash
        run: |
          echo "=== SAFE PARSE (here-string) ==="
          cat <<<"${{ github.event.issue.body }}"
          echo "=== DONE SAFE ==="

      - name: Check that no injected file exists (should be absent)
        run: |
          if [[ -f injected.txt ]]; then
            echo "::error::Unexpected injected.txt present after SAFE parse."
            exit 1
          else
            echo "OK: injected.txt not present."
          fi

      - name: VULNERABLE — print issue body via here-doc
        shell: bash
        run: |
          echo "=== VULNERABLE PARSE (here-doc) ==="
          cat <<'EOF'
            ${{ github.event.issue.body }}
          EOF
          echo "=== DONE VULNERABLE ==="

      - name: Check for injected file (runs even if previous step failed)
        if: ${{ always() }}
        run: |
          if [[ -f injected.txt ]]; then
            echo "Found injected.txt (proof of code execution):"
            ls -l injected.txt
            echo "Contents:"
            cat injected.txt
          else
            echo "No injected.txt present."
          fi
