name: Vulnerable Here-Doc via Issues
on:
  issues:
    types: [opened, edited]

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Parse issue body with here-doc (VULNERABLE)
        shell: bash
        run: |
          set +e
          REGEX='#### URL to issue\s*\n(https:\/\/biomage\.atlassian\.net\/browse\/BIOMAGE-[0-9]+|N\/A)'

          echo "::group::Running grep with here-doc (vulnerable)"
          grep -Po "$REGEX" <<'EOF'
          ${{ github.event.issue.body }}
          EOF
          echo "::endgroup::"

      - name: Show proof file (if present)
        if: ${{ always() }}
        run: |
          echo "::group::Checking for injected file"
          if [[ -f injected.txt ]]; then
            echo "Found injected.txt (proof of code execution):"
            ls -l injected.txt
            cat injected.txt
          else
            echo "No injected.txt present."
          fi
          echo "::endgroup::"
